---

repos:
# - repo: https://github.com/PyCQA/docformatter.git
#   rev: v1.7.5
#   hooks:
#   - id: docformatter
#     args:
#     - --in-place

- repo: https://github.com/Kludex/no-optional
  rev: 0.4.0
  hooks:
  - id: no_optional

- repo: https://github.com/python-jsonschema/check-jsonschema.git
  rev: 0.33.0
  hooks:
  - id: check-github-workflows
    files: ^\.github/workflows/[^/]+$
    types:
    - yaml
  - id: check-jsonschema
    name: Check GitHub Workflows set timeout-minutes
    args:
    - --builtin-schema
    - github-workflows-require-timeout
    files: ^\.github/workflows/[^/]+$
    types:
    - yaml
  - id: check-readthedocs

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v1.1.1
  hooks:
  - id: trailing-whitespace
    exclude: cherrypy/test/static/index.html
  - id: check-merge-conflict
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: name-tests-test
    include: cherrypy/test/
    args:
    - --django
    exclude: tests/dist-check.py
  - id: debug-statements
  - id: check-added-large-files
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-json
    include: .mention-bot
  - id: check-symlinks
  - id: check-yaml
  - id: detect-private-key
    exclude: cherrypy/test/test.pem
  - id: requirements-txt-fixer

- repo: https://github.com/PyCQA/pydocstyle.git
  rev: 6.3.0
  hooks:
  - id: pydocstyle

- repo: https://github.com/PyCQA/flake8.git
  rev: 7.1.0
  hooks:
  - id: flake8
    additional_dependencies:
    # - flake8-docstrings ~= 1.7.0
    # - flake8-docstrings-complete ~= 1.3.0
    - flake8-pyi ~= 24.1.0
    # - flake8-pytest-style ~= 1.7.2

- repo: https://github.com/Lucas-C/pre-commit-hooks.git
  rev: v1.5.4
  hooks:
  - id: remove-tabs

- repo: https://github.com/Lucas-C/pre-commit-hooks-lxml.git
  rev: v1.1.0
  hooks:
  - id: forbid-html-img-without-alt-text

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.34.0
  hooks:
  - id: yamllint
    files: \.(yaml|yml)$
    types: [file, yaml]
    args:
    - --strict

...
