---

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  # fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: >-  # PyYAML parses it as float but RTD demands an explicit string
      3.11

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
    - testing

...
